---
- name: Install RubyGems
  apt: name=rubygems state=present
  sudo: yes

- name: Install Capistrano gem
  gem:
    name: capistrano
    version: 2.9.0
    state: present

- name: Install sinatra gem
  gem:
    name: sinatra
    state: present

- name: Install rack gem
  gem:
    name: rack
    state: present

- name: Install thin gem
  gem:
    name: thin
    state: present

- name: Install json gem
  gem:
    name: json
    state: present

- name: Install titleize gem
  gem:
    name: titleize
    state: present

- name: Update hadoop user shell with cap binary path
  sudo: no
  lineinfile:
    dest: /home/hadoop/.bashrc
    insertafter: EOF
    line: 'export PATH="$PATH:/home/hadoop/.gem/ruby/1.8/bin/"'

- name: Download Hypertable vesion {{hypertable_version}}
  get_url: "url=http://cdn.hypertable.com/packages/{{hypertable_version}}/hypertable-{{hypertable_version}}-linux-x86_64.rpm dest=/home/hadoop/ owner=hadoop group=hadoop mode=0777"
  sudo: yes

- name: Copy default section of Capfile
  copy:
    src: Capfile.cluster
    dest: /home/hadoop/Capfile
    owner: hadoop
    group: hadoop

- name: Append cluster management capfile User Configs
  lineinfile:
    dest: /home/hadoop/Capfile
    insertbefore: BOF
    line: "{{ lookup('file', 'Capfile.user_config.json.j2') }}"

- name: Copy Master ssh public key to local
  fetch:
    src: /home/hadoop/.ssh/id_rsa
    dest: "./roles/ssh/files/id_rsa"
    flat: yes



