# TODO
# curl -sSL https://get.rvm.io | bash -s stable
#    33  vi .bash_profile
#    51  rvm install 2.1.2
#    54  rvm gemset install latest
#    58  rvm gemset create fizzingpanda
#    59  rvm gemset use fizzingpanda
#    60  gem install capistrano -v 2.9.0

---
# - name: Install RVM
#   shell: curl -sSL https://get.rvm.io | bash -s stable
#   sudo: yes

# - name: Install Ruby
#   shell: 

- name: Install RubyGems
  apt: name=rubygems state=present
  sudo: yes

- name: Install Capistrano gem
  gem:
    name: capistrano
    version: 2.9.0
    state: present

- name: Install sinatra gem
  gem:
    name: sinatra
    state: present

- name: Install rack gem
  gem:
    name: rack
    state: present

- name: Install thin gem
  gem:
    name: thin
    state: present

- name: Install json gem
  gem:
    name: json
    state: present

- name: Install titleize gem
  gem:
    name: titleize
    state: present

- name: Update hadoop user shell with cap binary path
  sudo: no
  lineinfile:
    dest: /home/hadoop/.bashrc
    insertafter: EOF
    line: 'export PATH="$PATH:/home/hadoop/.gem/ruby/1.8/bin/"'

# - name: Install Capistrano Gem.  Version 2.9 works!!!
#   shell: gem install capistrano -v 2.9.0
#   sudo: yes

- name: Download Hypertable vesion {{hypertable_version}}
  get_url: "url=http://cdn.hypertable.com/packages/{{hypertable_version}}/hypertable-{{hypertable_version}}-linux-x86_64.rpm dest=/home/hadoop/ owner=hadoop group=hadoop mode=0777"
  sudo: yes

# - name: Unarchive Hypertable archive
#   unarchive: src=/home/hadoop/hypertable-0.9.8.0-linux-x86_64.tar.bz2 dest=/home/hadoop copy=no

- name: Copy default section of Capfile
  copy:
    src: Capfile.cluster
    dest: /home/hadoop/Capfile
    owner: hadoop
    group: hadoop

- name: Append cluster management capfile User Configs
  lineinfile:
    dest: /home/hadoop/Capfile
    insertbefore: BOF
    line: "{{ lookup('file', 'Capfile.user_config.json.j2') }}"

- name: Create Hypertable Directory /etc/opt/hypertable
  file: path=/etc/opt/hypertable owner=hadoop group=hadoop state=directory recurse=yes
  sudo: yes

- name: Create Hypertable Directory /var/opt/hypertable
  file: path=/var/opt/hypertable owner=hadoop group=hadoop state=directory recurse=yes
  sudo: yes

- name: Create Hypertable Directory /opt/hypertable
  file: path=/opt/hypertable owner=hadoop group=hadoop state=directory recurse=yes
  sudo: yes

# TODO:  Complete testing on nodes
- name: Copy Master ssh public key to local
  fetch:
    src: /home/hadoop/.ssh/id_rsa
    dest: "./roles/ssh/files/id_rsa"
    flat: yes



