---
- name: Install RubyGems
  apt: name=rubygems state=present
  sudo: yes

- name: Install Capistrano gem
  gem:
    name: capistrano
    version: 2.9.0
    state: present

- name: Install sinatra gem
  gem:
    name: sinatra
    state: present

- name: Install rack gem
  gem:
    name: rack
    state: present

- name: Install thin gem
  gem:
    name: thin
    state: present

- name: Install json gem
  gem:
    name: json
    state: present

- name: Install titleize gem
  gem:
    name: titleize
    state: present

- name: Update hadoop user shell with cap binary path
  sudo: no
  lineinfile:
    dest: /home/hadoop/.bashrc
    insertafter: EOF
    line: 'export PATH="$PATH:/home/hadoop/.gem/ruby/1.8/bin/"'

- name: Copy Master ssh public key to local
  fetch:
    src: /home/hadoop/.ssh/id_rsa
    dest: "./roles/ssh/files/id_rsa"
    flat: yes



