---
- name: Backup all tables
  hosts: masters
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
    id: "{{ lookup('file', './id') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - backup