---
- name: Backup all tables
  hosts: masters
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
     master: "{{ lookup('file', './panda3T_masters') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - backup