---
- name: Build AWS EMR Cluster
  hosts: build
  user: teknik
  sudo: false
  gather_facts: false
  roles:
    - emr

- name: Configure each Master Node for Hypertable
  hosts: cluster_master
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
     etc_hosts: "{{ lookup('file', './panda_etc_hosts') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - newrelic
    - dns
    - nodes_master

- name: Configure each CORE Node for Hypertable
  hosts: cluster_cores
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
     etc_hosts: "{{ lookup('file', './panda_etc_hosts') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - newrelic
    - dns
    - ssh
    - nodes_core

- name: Configure each CORE Node for Hypertable
  hosts: cluster_tasks
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
     etc_hosts: "{{ lookup('file', './panda_etc_hosts') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - newrelic
    - dns
    - ssh
    - nodes_task

- name: Build Hypertable on Master1
  hosts: cluster_master
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
     etc_hosts: "{{ lookup('file', './panda_etc_hosts') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - hypertable
