---
- name: Build AWS EMR Cluster
  hosts: build
  user: teknik
  sudo: false
  gather_facts: false
  roles:
    - cluster

- name: Configure each Master Node
  hosts: cluster_master
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
    id: "{{ lookup('file', './id') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - dns
    - newrelic
    - nodes
    - nodes_master

- name: Configure each CORE Node
  hosts: cluster_cores
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
    id: "{{ lookup('file', './id') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - newrelic
    - dns
    - ssh
    - nodes
    - nodes_core

- name: Configure each TASK Node
  hosts: cluster_tasks
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
    id: "{{ lookup('file', './id') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - newrelic
    - dns
    - ssh
    - nodes
    - nodes_task

- name: Build Hypertable on Master1
  hosts: cluster_master
  user: hadoop
  sudo: false
  gather_facts: false
  vars_files:
    - ./group_vars/build
  roles:
    - hypertable
