---
- name: Load ALL FP data from ebs mount
  hosts: masters
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
     masters: "{{ lookup('file', './panda6_masters') }}"
     profile: usp
  roles:
    - ec2
    - load