---
- name: Load ALL FP data from ebs mount
  hosts: masters
  user: hadoop
  sudo: false
  gather_facts: false
  vars:
     masters: "{{ lookup('file', './panda_masters') }}"
  vars_files:
    - ./group_vars/build
  roles:
    - ec2
    - load