---
- name: Load Panda DB Schema
  shell: cat /data/panda/source/schema.hql | /opt/hypertable/current/bin/ht shell

- name: Load data into table counts1
  shell: cat /data/panda/source/counts1/load.hql | /opt/hypertable/current/bin/ht shell

- name: Load data into table jointcount
  shell: cat /data/panda/source/counts1/load.hql | /opt/hypertable/current/bin/ht shell

- name: Load data into table doc
  shell: cat /data/panda/source/doc/load.hql | /opt/hypertable/current/bin/ht shell

- name: Load data into table counts2
  shell: cat /data/panda/source/counts2/load.hql | /opt/hypertable/current/bin/ht shell

- name: Load data into table concept
  shell: cat /data/panda/source/concept/load.hql | /opt/hypertable/current/bin/ht shell