---
- name: Create Hypertable Directory /etc/opt/hypertable
  file: path=/etc/opt/hypertable owner=hadoop group=hadoop state=directory recurse=yes
  sudo: yes

- name: Create Hypertable Directory /var/opt/hypertable
  file: path=/var/opt/hypertable owner=hadoop group=hadoop state=directory recurse=yes
  sudo: yes

- name: Create Hypertable Directory /opt/hypertable
  file: path=/opt/hypertable owner=hadoop group=hadoop state=directory recurse=yes
  sudo: yes