---
- name: Installing Hypertable RPM
  command: cap install_package

- name: Copying Hypertable binaries to cluster nodes
  shell: cap dist

- name: FHS-ize the installation FHS-ize the installation 
  shell: cap fhsize

- name: Set "current" link
  shell: cap set_current

- name: Create Hypertable Config file
  template: 
    src: hypertable.json.j2
    dest: "/opt/hypertable/hypertable.cfg"

- name: Copying Hypertable binaries to cluster nodes
  shell: cap push_config

- name: Start hyperspace
  shell: cap start_hyperspace

# TODO: Master starts HOWEVER errors out because monitoring fails to start
- name: Start master
  shell: cap start_master
  ignore_errors: yes

- name: Start slaves
  shell: cap start_slaves