---
- name: Configure the New Relic apt repository
  shell: echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
  sudo: yes

- name: Trust the New Relic GPG key
  shell: wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
  sudo: yes

- name: Update the local package list.
  shell: apt-get update
  sudo: yes

- name: Install the Server Monitor package
  shell: apt-get install newrelic-sysmond
  sudo: yes

- name: Configure Server Monitor daemon with license
  shell: "nrsysmond-config --set license_key={{newrelic}}"
  sudo: yes
  when: newrelic is defined

- name: Start the daemon
  shell: /etc/init.d/newrelic-sysmond start
  sudo: yes